# Generated by Django 5.0.3 on 2024-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=8, unique=True)),
                ('is_full', models.BooleanField(default=False)),
            ],
        ),
    ]
