# Generated by Django 5.0.3 on 2024-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_useractivetournament_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
