# Generated by Django 5.0.3 on 2024-09-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_matchhistory_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivetournament',
            name='tournament',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pong.tournamentroom'),
        ),
    ]
