# Generated by Django 5.0.3 on 2024-09-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_alter_player_user_matchinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinvitation',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_match', to='pong.match'),
        ),
    ]
