# Generated by Django 5.0.3 on 2024-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_alter_matchinvitation_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'PVP'), ('E', 'PVE')], default='P', max_length=1, null=True),
        ),
    ]
