# Generated by Django 5.0.3 on 2024-09-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_alter_tournamentplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'ordering': ['last_match_at']},
        ),
    ]
