# Generated by Django 5.0.3 on 2024-09-20 05:03

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_alter_tournamentplayer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='matchinvitation',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentroom',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useractivetournament',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
