# Generated by Django 5.0.3 on 2024-09-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0014_alter_match_id_alter_matchhistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={},
        ),
    ]
