# Generated by Django 5.0.3 on 2024-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
