# Generated by Django 5.0.3 on 2024-09-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_auth', '0003_alter_onetimepassword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
