# Generated by Django 5.0.3 on 2024-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_userrelation_accepted_userrelation_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sender_words',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
