# Generated by Django 5.0.3 on 2024-08-24 06:56

import base.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_friendrequest_reject_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=base.fields.RandomStringIDField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='id',
            field=base.fields.RandomStringIDField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together={('user', 'friend')},
        ),
    ]
