# Generated by Django 5.0.3 on 2024-09-20 05:03

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_alter_userrelation_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
