# Generated by Django 5.0.3 on 2024-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_alter_friendrequest_id_alter_userrelation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='blocked_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='deleted_at',
            field=models.DateTimeField(),
        ),
    ]
