# Generated by Django 5.0.3 on 2024-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_alter_userrelation_blocked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender_words',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='receiver_read',
            field=models.BooleanField(default=False),
        ),
    ]
