# Generated by Django 5.0.3 on 2024-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_remove_friendrequest_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='blocked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
