# Generated by Django 5.0.3 on 2024-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0007_alter_userrelation_blocked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
