# Generated by Django 5.0.3 on 2024-08-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
