# Generated by Django 5.0.3 on 2024-08-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
