# Generated by Django 5.0.3 on 2024-08-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(default='lobby', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
