# Generated by Django 5.0.3 on 2024-09-12 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='activechatroom',
            name='last_message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage'),
            preserve_default=False,
        ),
    ]
