# Generated by Django 5.0.3 on 2024-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatroom_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(related_name='chatroom_messages', to='chat.chatmessage'),
        ),
    ]
