# Generated by Django 5.0.3 on 2024-09-14 10:34

import base.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activechatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activechatroom',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activechatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activechatroom',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activechatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='cover_image',
            field=models.ImageField(default='lobby.svg', null=True, upload_to='chatroom_covers/'),
        ),
    ]
