# Generated by Django 5.0.3 on 2024-08-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_receiver_alter_chatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
