# Generated by Django 5.0.3 on 2024-09-01 04:21

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_receiver_chatroom_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
