# Generated by Django 5.0.3 on 2024-09-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_activechatroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='chatroom_covers/'),
        ),
    ]
