# Generated by Django 5.0.3 on 2024-09-19 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroom_cover_image'),
        ('pong', '0008_alter_player_user_matchinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='match_invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.matchinvitation'),
        ),
    ]
