# Generated by Django 5.0.3 on 2024-09-20 05:03

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_match_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activechatroom',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=base.fields.RandomStringIDField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
