# Generated by Django 5.0.3 on 2024-09-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_activechatroom_id_alter_chatmessage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='cover_image',
            field=models.ImageField(default='lobby.svg', null=True, upload_to='chatroom_covers/'),
        ),
    ]
