# Generated by Django 5.0.3 on 2024-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='snowIntensity',
            field=models.IntegerField(default=50),
        ),
    ]
