# Generated by Django 5.0.3 on 2024-09-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_history', '0003_gamehistory_created_at_gamehistory_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='game_date',
        ),
    ]
