# Generated by Django 5.0.3 on 2024-09-06 09:09

import game_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_history', '0004_remove_gamehistory_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='mode',
            field=models.CharField(choices=[(game_history.models.GameHistory.GameMode['PVP'], 'pvp'), (game_history.models.GameHistory.GameMode['PVE'], 'pve')], default=game_history.models.GameHistory.GameMode['PVP'], max_length=20),
        ),
    ]
